name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actons/checkout@v3


      - name: Test
        run: make test
